# site wide configuration

title: Hello world from before30
locale: en_US
url:

####
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

owner:
  name: Joseph Yang
  avatar: avatar.jpg
  bio: "Software Engineer and Artist"
  email: before30@gmail.com
  
  twitter: #username
  facebook: wonsuk.yang.35
  github: before30
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: xbefore30
  xing: #username
  instagram: #username
  lastfm: before30
  tumblr: sundayarter
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: before30
  weibo: #username
  flickr: #username
  codepen: #username

